image: ruby:2.6.4

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - bundle install --path vendor/bundle

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  cache:
    key: ${CI_PROJECT_PATH}
    paths:
      - vendor/bundle
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  cache:
    key: ${CI_PROJECT_PATH}
    paths:
      - vendor/bundle
  artifacts:
    paths:
    - public
  only:
  - master
