image: ruby:2.6.4

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - bundle install

test:
  stage: test
  script:
  - bundle install --path vendor/bundle
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
    - vendor/bundle
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle install --path vendor/bundle
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
    - vendor/bundle
  only:
  - master
