# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# This is how Jekyll knows to use this theme.
theme: jekyll-theme-portfolio
author: Jeffrey Harris

# Header Links - all optional. If set these create header links.
header_pages:
  - about.md
  - portfolio.md

homepage: https://jeffharris.us
permalink: /:categories/:title/


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme # Lets us test remote themes locally.

title: Portfolio of Jeffrey Harris
whatis: >
  A curated list of public projects created by Jeffrey Harris.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jefharris.us" # the base hostname & protocol for your site
timezone: America/Los_Angeles
source: app
locale: "en-US"

# Build settings
markdown: kramdown
toc_levels: 1..6

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Author settings
email: jeff@jeffharris.us
github_username: jefhar
gitlab_username: jefhar
linkedin_username: jeff-harris-9b609814a
twitter_username: jefhar70

description: > #
  Re-entry student pursuing a Bachelors in Computer Science with an emphasis in
  Software Engineering. Projected graduation in June 2021.
